### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by mitchsfm** [beta-tester/RPi-GPS-PPS-StratumOne#4]
Using RPi 3, Adafruit GPS V3. Have fix, have data, have pps out of gps.:

output of sudo ppswatch -a /dev/pps0 attached
gpsmon output attached.
cgps output attached.
Suggestions for troubleshooting?
tx from gps to rx pin 10 of rpi header.
rx from gps to tx pin 8 of rpi header
pps from gps to pin 7 of rpi header

Tnx for any help.
![screen shot 2018-04-02 at 1 05 47 am](https://user-images.githubusercontent.com/9885449/38185105-2b035e1e-3612-11e8-9340-c93fbdb699b8.png)
![screen shot 2018-04-02 at 12 55 18 am](https://user-images.githubusercontent.com/9885449/38185106-2b12987a-3612-11e8-9f5a-18c738d72200.png)
![screen shot 2018-04-02 at 12 59 14 am](https://user-images.githubusercontent.com/9885449/38185107-2b221fa2-3612-11e8-82e2-9521ab17bdf1.png)

Mitch 
Opelika, AL
mitchsfm@gmail.com

**Comment by beta-tester** [comment]
did you used the script without modification?
did you used Raspbian Stretch 2018-03-13 without installing other stuff?
is the gps module attached correctly?

how do you know, that you have a FIX?

there is something detecting on the GPIO pin 4 (pin 7 on the HAT connector), otherwise ppswatch would show timeouts only.
i guess, the extreme high offset values (its unit is [ns]) will be normal because of missing time sync.
(the differences between two offsets are in the range of ns and µs that looks good)

but you do not get any gps data (time and coordinates).
is TX and RX connected propely or did you swapped the cables by accident?
TX of GPS module goes to RX of RPi.
RX pf GPS module goes to TX of RPi.
see picture: [Using UART instead of USB](https://learn.adafruit.com/adafruit-ultimate-gps-on-the-raspberry-pi/using-uart-instead-of-usb)

is the baud rate setted up correctly?

**Comment by mitchsfm** [comment]
Thanks for the very quick response.

The gps is connected correctly, quadruple checked. I am suspecting wrong
baud rate. I will make another sd card with just a terminal program and
determine the baud rate coming from the gps. I am assuming correct baud
rate is 9600 and standard nmea 0183 data sequence is required from the gps.

Mitch

**Comment by mitchsfm** [comment]
Ok, much progress.

Was using rpi 3+, wasn't working.
Tried rpi zero w with ethernet, gps not getting fix, trouble shoot later.
Working!!! with rpi 2!!!

All sources are pps and NMEA. See below.

Thanks!
Mitch

*pi@ntp*:*~ $* chronyc sourcestats

210 Number of sources = 4

Name/IP Address            NP  NR  Span  Frequency  Freq Skew  Offset  Std
Dev

==============================================================================

PPS                         6   5    66     -0.012      0.063    -69ns
391ns

PPSx                       14  10   103     -0.007      0.018    -10ns
392ns

PPSy                       15   9   115     -0.005      0.014    +64ns
376ns

NMEA                        6   3    41  +2735.537  43464.031   -110ms
164ms


*pi@ntp*:*~ $* chronyc tracking

Reference ID    : 50505300 (PPS)

Stratum         : 1

Ref time (UTC)  : Mon Apr 02 15:23:41 2018

System time     : 0.000000066 seconds slow of NTP time

Last offset     : -0.000000082 seconds

RMS offset      : 0.000002072 seconds

Frequency       : 7.643 ppm fast

Residual freq   : -0.001 ppm

Skew            : 0.041 ppm

Root delay      : 0.000000 seconds

Root dispersion : 0.000009 seconds

Update interval : 8.0 seconds

Leap status     : Normal

**Comment by beta-tester** [comment]
yesterday an other user was reporting an issue with an RPi3, it was because of the built-in bluetooth interface, that is hijacking the serial port.
gpsd was throwing errors because of a busy serial port.
the user disabled the bluetooth interface by adding "dtoverlay=pi3-disable-bt" to the config.txt file.

i added that option to my script yeaterday... but maybe i made something wrong in my script.

if you have time and possibility, would it be possible to test,
if you can get the RPi3+ working when you

1. install Raspbian Stretch to the SD card newly,
2.  then `sudo raspi-config` to disable the bluetooth interface there,
3. then run my script.


maybe there is more going on then disabling the bluetooth via raspi-config.

**Comment by mitchsfm** [comment]
Yes, I will pleased to test rpi 3+.

Will find another sd card and program, will report back with rpi 3+ results.

Working!!! with rpi 3+, see below.

Thanks
Mitch

**Comment by mitchsfm** [comment]
Forgot to volunteer to test, I have just about all rpi models.

Great program! I will use it for ham radio, to set time for digital
transmissions. Way overkill, but fun!

Mitch

**Comment by beta-tester** [comment]
i have my gps-pps-timeserver running on an old RPi1 rev1 with 256MB... just enough computer power for that purpose ... :)

you got it working on an RPi3+ ... by using just the script or with help of raspi-conf ? 
does that means my script still isn't working for RPi3 correctly, even not with the changes i made yeaterday, and the built-in bluetooth interface still has to be disabled via raspi-conf?

can you please provide your config.txt file

**Comment by mitchsfm** [comment]
On rpi3+, I used raspi-config only to change pw, set tz to cdt time, and
expand sd card.  Then cloned script, made executable and ran. Ran ok, no
changes made.

I will dig out my rpi 1 and try it, if runs ok, I will use it for permanent
install.

Thanks again!

Mitch

**Comment by beta-tester** [comment]
so i can keep my script as it is - but for safety i added a commen to the README file.

thank you for reporting, testing and giving feedback.

**Comment by mitchsfm** [comment]
Stretch-lite,  latest version, no mods to the script .

**Comment by mitchsfm** [comment]
I just installed your StratumOne script on another RPi Zero W as I found
another gps module in my junk box that I had bought or another project. In
addition to disabling the serial login and serial hardware using
raspi-config, bluetooth has to be disabled.

This is easily done by:
sudo nano /boot/config.txt
Adding at the end of config.txt:
# turn bluetooth off
dtoverlay=pi3-disable-bt
Then reboot.

Regards,
Mitch

**Comment by beta-tester** [comment]
ok,
the script creates a config.txt file that has conditional parts for different RPis.i forgot to add a conditional part for RPi0 then.
```
#this i have
[pi3]
dtoverlay=pi3-disable-bt

#this i forgot
[pi0]
dtoverlay=pi3-disable-bt

[all]
... 
```
better, i set this option for all RPi's, even for RPi1 and RPi2... i think it will not produce any conflicts if no built-in bluetooth interface is available there.

thank you very much for testing...
